### PR TITLE
alerts users that they are not logged in when viewing profiles.

### PR DESCRIPTION
**Pull request by ebbnormal**
@wandp I don't know where the templates are so currently i am just displaying an alert, but I would like to edit the ArtistDetailCtrl template to hide the page content as well as the song in the case of unauthorized. When you get a chance kindly point out its location to me :) Ryan.

### CODE REVIEW

**Comment by wandp** [comment]
they are located here:
https://raw.githubusercontent.com/wandp/song-a-day-for-a-month/gh-pages/js/app_templates.js

**Comment by ebbnormal** [comment]
@wandp awesome! you are a wild developer sir. I have never seen anybody write code as aesthetically pleasing and as idiosyncratically as you. i love having all templates on a single line of a js file. wild!

**Comment by wandp** [comment]
originally, they had their own separate files and would be compiled into this document via gulp https://github.com/wandp/song-a-day-ionic/tree/master/app/templates

**Comment by ebbnormal** [comment]
@wandp do you have any model-like files which describe the attributes JSON returned by the FBURL resources? I was thinking of either in this PR or in another one adding a `isProfilePublic` attribute to an account/ artist model but I don't know where I could both define that attribute and set it in the `AccountCtrl`?

**Comment by ebbnormal** [comment]
@wandp it is ready to rawk!

**Comment by wandp** [comment]
aight its live on http://www.sadfam.com/

**Pull request merged**
